###
GET http://localhost:3000/api/clientes

###
GET http://localhost:3000/api/clientes/155

###
GET http://localhost:3000/api/clientes/mayores/60

###
POST  http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Macarena",
    "apellidos": "Martin de Castro",
    "direccion": "Avenida Andalucia Nº164 1D",
    "email": "macarena.martin.decastro99@gmail.com",
    "edad": 23,
    "genero": "F",
    "cuota": 39.90,
    "fecha_nacimiento": "1960-11-20", 
    "dni": "77768417n"
}

###
PUT http://localhost:3000/api/clientes/155
Content-Type: application/json

{
    "nombre": "Macanena",
    "apellidos": "Martin ade Castro",
    "direccion": "Avenida Andalucia Nº164 1D",
    "email": "makapimpampum99@gmail.com",
    "edad": 23,
    "genero": "F",
    "cuota": 39.90,
    "fecha_nacimiento": "1960-11-20", 
    "dni": "77768417n"
}

###
DELETE http://localhost:3000/api/clientes/175