### API CLIENTES
GET http://localhost:3000/api/clientes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NTYyMzkyLCJpYXQiOjE2Njc1NTUxOTJ9.MkGgHlmMnaQciD311DYCl6U4VLfSlOBq3o68QLEZAGA

###
GET http://localhost:3000/api/clientes/108
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NTYyMzkyLCJpYXQiOjE2Njc1NTUxOTJ9.MkGgHlmMnaQciD311DYCl6U4VLfSlOBq3o68QLEZAGA

###
GET http://localhost:3000/api/clientes/mayores/70
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NDczNzc0LCJpYXQiOjE2Njc0NjY1NzR9.ACfbSDok2CaHQjPs-VkkKbwDToQNQtDKWTgSk9AB_Nk

###
POST http://localhost:3000/api/clientes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NTcwNDI4LCJpYXQiOjE2Njc1NjMyMjh9.e_87FktzFFEm1wInOOCIpbTRMHMnZ9r0_zns6NVtJb8

{
    "nombre": "Lorenzo",
    "apellidos": "Romero",
    "direccion": "C/ Ballesta 23",
    "email": "dd@gmail.com",
    "edad": 18,
    "genero": "m",
    "cuota": "39.90",
    "fecha_nacimiento": "1953-07-23",
    "dni": "78988772K"
}

###
PUT http://localhost:3000/api/clientes/111
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NTcwNDI4LCJpYXQiOjE2Njc1NjMyMjh9.e_87FktzFFEm1wInOOCIpbTRMHMnZ9r0_zns6NVtJb8

{
  "nombre": "Pepe",
  "apellidos": "García",
  "direccion": "Calle Pico de los artilleros 45",
  "email": "lauragar@gmail.com",
  "edad": 74,
  "genero": "f",
  "cuota": "19.90",
  "fecha_nacimiento": "1978-08-11",
  "dni": "99919289Y"
}

###
DELETE http://localhost:3000/api/clientes/124
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NTYyMzkyLCJpYXQiOjE2Njc1NTUxOTJ9.MkGgHlmMnaQciD311DYCl6U4VLfSlOBq3o68QLEZAGA

### API PROFESORES
GET http://localhost:3000/api/profesores
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NDczNzc0LCJpYXQiOjE2Njc0NjY1NzR9.ACfbSDok2CaHQjPs-VkkKbwDToQNQtDKWTgSk9AB_Nk

###
GET http://localhost:3000/api/profesores/clientes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJ1c2VyUm9sZSI6ImFkbWluIiwiZXhwaXJlc0F0IjoxNjY3NDczNzc0LCJpYXQiOjE2Njc0NjY1NzR9.ACfbSDok2CaHQjPs-VkkKbwDToQNQtDKWTgSk9AB_Nk


###
POST http://localhost:3000/api/profesores
Content-Type: application/json

{
    "nombre": "María",
    "experiencia": 3,
    "hora_entrada": "09:00:00",
    "hora_salida": "15:00:00"
}

###
PUT http://localhost:3000/api/profesores/12

###
DELETE http://localhost:3000/api/profesores/45    