GET http://localhost:3000/clients

###
GET http://localhost:3000/clients/new

###
GET http://localhost:3000/clients/edit

###
GET http://localhost:3000/clients/delete

###
POST http://localhost:3000/clients/create

###
POST http://localhost:3000/clients/update

###
GET http://localhost:3000/clients/1212

###
GET http://localhost:3000/clients/12/budget/9898

#################
## Pruebas API ##
#################
GET http://localhost:3000/api/clients?page=3

###
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "name": "Laura López",
    "email": "laurita@gmail.com",
    "phone": "66712123",
    "address": "C/ Barco 45"
}